### ISSUE TITLE
User Flow for getting Local Weather

### ISSUE THREAD

**Issue by EngineeringDeveloper** [EngineeringDeveloper/layers#3]

**Comment by EngineeringDeveloper** [comment]
@tommichaelford 
I guess the general flow is

- User allows permissions for location sharing
    - Handle rejection of permissions
- Make API request for Weather details
    - Handle rejection States of API call
- Parse and Display Returned Weather Data
- Hand Weather Data to Further function to Make the Recomendation 

Do you want to start on this and ill Look at pencilling out the structure for  How we can decide what to suggest?

**Comment by tommichaelford** [comment]
Sounds good to me

**Comment by EngineeringDeveloper** [comment]
The type OpenWeatherCurrentResponse doesnt have any information about Rail levels?
